#ifndef PAYLOADTYPE_H
#define PAYLOADTYPE_H

enum ClientPayloadType {
	CLIENTPAYLOADTYPE_SYSTEMINFO,
	CLIENTPAYLOADTYPE_HEARTBEAT,
	CLIENTPAYLOADTYPE_COUNT
};

enum ServerPayloadType {
	SERVERPAYLOADTYPE_REQUESTSYSTEMINFO,
	SERVERPAYLOADTYPE_COUNT
};

#endif
