#ifndef PAYLOADTYPE_H
#define PAYLOADTYPE_H

enum ClientPayloadInType {
	CLIENTPAYLOADTYPE_SYSTEMINFO,
	CLIENTPAYLOADTYPE_HEARTBEAT,
	CLIENTPAYLOADTYPE_COUNT
};

enum ServerPayloadOutType {
	SERVERPAYLOADTYPE_REQUESTSYSTEMINFO,
	SERVERPAYLOADTYPE_COUNT
};

#endif
