#ifndef PAYLOADTYPE_H
#define PAYLOADTYPE_H

enum ClientPayloadType {
	CLIENTPAYLOADTYPE_SYSTEMINFO,
	CLIENTPAYLOADTYPE_HEARTBEAT
};

enum ServerPayloadType {
	SERVERPAYLOADTYPE_REQUESTSYSTEMINFO
};

#endif
