#ifndef PAYLOADTYPE_H
#define PAYLOADTYPE_H

enum ClientPayloadOutType {
	CLIENTPAYLOADTYPE_SYSTEMINFO,
	CLIENTPAYLOADTYPE_HEARTBEAT,
	CLIENTPAYLOADTYPE_COUNT
};

enum ServerPayloadInType {
	SERVERPAYLOADTYPE_REQUESTSYSTEMINFO,
	SERVERPAYLOADTYPE_COUNT
};

#endif
